<?php

namespace hflan\GuestbookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function count()
    {
        $qb = $this->createQueryBuilder('a')
            ->select('COUNT(a)');

        return (int) $qb->getQuery()
            ->getSingleScalarResult();
    }

    public function getTotalPages($messagesPerPage)
    {
        return max(1, ceil( $this->count() / $messagesPerPage ));
    }

    public function getPage($page, $messagesPerPage)
    {
        if( $page < 1 OR $page > $this->getTotalPages($messagesPerPage) )
            return false;

        return $this->findBy(
            array(),
            array('created_at' => 'desc', 'id' => 'desc'),
            $messagesPerPage,
            ($page-1) * $messagesPerPage
        );
    }
}
