<?php

namespace hflan\TournamentBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\AbstractQuery;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function getNextEvent()
    {
        $queryBuilder = $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.start_at > :now')
                ->setParameter('now', new \Datetime)
            ->andWhere('a.public = true')
            ->setMaxResults(1);

        $query = $queryBuilder->getQuery();

        try
        {
            return $query->getSingleResult(AbstractQuery::HYDRATE_OBJECT);
        }
        catch(NoResultException $e)
        {
            return null;
        }
    }
}
