<?php

namespace hflan\TournamentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
    public function getTeamsByTournament(Tournament $tournament, $confirmed)
    {
        //$queryBuilder = $this->createQueryBuilder('a');

        //return $queryBuilder->getQuery()->getResult();

        return $this->findBy(array('tournament'=>$tournament, 'confirmed'=>$confirmed), array('created_at'=>'ASC'));
    }

    public function getConfirmed(Tournament $tournament)
    {
        return $this->getTeamsByTournament($tournament, true);
    }

    public function getPending(Tournament $tournament)
    {
        return $this->getTeamsByTournament($tournament, false);
    }
}
